[env:lolin_c3_mini]
platform = espressif32
board = lolin_c3_mini
framework = arduino
monitor_speed = 115200
lib_deps = 
    adafruit/Adafruit BME280 Library@^2.2.4
    adafruit/Adafruit Unified Sensor@^1.1.14
    knolleary/PubSubClient@^2.8
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library
    adafruit/Adafruit LTR390 Library
