[env:ttgo-t-watch]
platform = espressif32
board = ttgo-t-watch
framework = arduino
monitor_speed = 115200
lib_deps = 
    bodmer/TFT_eSPI
    bodmer/TJpg_Decoder
    bblanchon/ArduinoJson
    knolleary/PubSubClient
extra_scripts = post:scripts/fix_map_path.py
build_flags = 
    -DUSER_SETUP_LOADED=1
    -DST7789_DRIVER=1
    -DTFT_CS=5
    -DTFT_DC=27
    -DTFT_RST=-1
    -DTFT_MOSI=19
    -DTFT_SCLK=18
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=240
    -DSPI_FREQUENCY=40000000
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DLOAD_FONT4=1
    -DLOAD_FONT7=1
    -DSMOOTH_FONT=1
    -DHTTPCLIENT_HAS_GZIP=1